algoritmo " respota LETRA A"
// Função : 2) Analise os algoritmos abaixo e diga o que será impresso na tela ao serem executados:
// Autor :   ANDRE COSTA
// Data : 08/03/2023
// Seção de Declarações 
var
 a , b : inteiro
inicio
// Seção de Comandos 
escreval ("questão 2 letra A")
a:=10
b:=20
escreval("B RECEBEU", b)
b:=5
escreval ("B RECEBEU", b)
escreval ("RESPOSTA")
escreval ("quando se atribui um novo valor para a variavel declarada ela muda o valor")
fimalgoritmo
