algoritmo " RESPOSTAS QUESTÃO 5"
// Função :) ) Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela) o seu antecessor.
// Autor :   ANDRE COSTA
// Data : 08/03/2023
// Seção de Declarações
var
d , ant: inteiro
inicio
// Seção de Comandos
 escreval ("Digite um numero")
 leia(d)
ant:=d-1
 escreval("O seu antecessor é:", ant)

escreval ("")
escreval ("")
escreval  (" /\_/\")
escreval  ("(>'.'<)")
escreval  ("(U   U)")
escreval ("__~^_^~__")
fimalgoritmo
